// app/guides/nextjs-accessibility/page.tsx
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Next.js accessibility — WCAG 2.1 AA checklist + CI setup (2026)",
  description:
    "Practical accessibility for Next.js apps: App Router SSR a11y, Image component alt text, Link vs anchor, forms, focus management, and how to put axe-core in CI so regressions fail your PR builds.",
  keywords: [
    "Next.js accessibility",
    "Next.js a11y",
    "WCAG Next.js",
    "App Router accessibility",
    "Next.js axe-core",
    "React accessibility CI",
    "EAA Next.js",
    "axle",
  ],
  openGraph: {
    title: "Next.js accessibility — a practical WCAG 2.1 AA guide",
    description:
      "App Router specifics, the pieces most developers get wrong, and a copy-paste CI setup that blocks merges on accessibility regressions.",
    type: "article",
    locale: "en_US",
  },
  alternates: { canonical: "/guides/nextjs-accessibility" },
};

export default function NextjsPage() {
  return (
    <main className="min-h-screen bg-slate-50">
      <article className="mx-auto max-w-3xl px-6 py-12">
        <p className="text-xs font-semibold uppercase tracking-wider text-slate-500">
          Next.js · accessibility engineering
        </p>
        <h1 className="mt-2 text-4xl font-bold tracking-tight text-slate-900">
          Next.js accessibility — a practical WCAG 2.1 AA guide
        </h1>
        <p className="mt-4 text-lg text-slate-700">
          Next.js gives you SSR, Image optimisation, and a routing system that developers
          love. It does not give you accessibility for free. This guide covers the Next.js
          specifics — App Router SSR quirks, the Image and Link components, form
          interactions, and focus management — plus a copy-paste CI pipeline that blocks
          merges on WCAG regressions. Written for Next 14 / 15 / 16.
        </p>

        <nav className="mt-8 rounded-lg border border-slate-200 bg-white p-4 text-sm">
          <div className="text-xs font-semibold uppercase tracking-wider text-slate-500">
            Contents
          </div>
          <ol className="mt-2 list-decimal space-y-1 ps-6 text-slate-700">
            <li><a className="hover:underline" href="#html-lang">Declare language on the html tag (App Router)</a></li>
            <li><a className="hover:underline" href="#images">The Image component — alt text and decorative images</a></li>
            <li><a className="hover:underline" href="#links">Link vs anchor vs button</a></li>
            <li><a className="hover:underline" href="#forms">Form labels and error messaging</a></li>
            <li><a className="hover:underline" href="#focus">Focus management on client-side navigation</a></li>
            <li><a className="hover:underline" href="#headings">Heading hierarchy across the App Router tree</a></li>
            <li><a className="hover:underline" href="#dialog">Dialogs and overlays — the 5 requirements</a></li>
            <li><a className="hover:underline" href="#ci">CI setup — block regressions in every PR</a></li>
          </ol>
        </nav>

        <section id="html-lang" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">
            Declare language on the html tag
          </h2>
          <p className="mt-3 text-slate-700">
            WCAG 3.1.1 requires each page declares its primary language. In App Router,
            this lives in the root <code>app/layout.tsx</code>:
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-xs leading-snug text-slate-100"><code>{`// app/layout.tsx
export default function RootLayout({ children }) {
  return (
    <html lang="en">    {/* or "he", "de", "fr" for localised sites */}
      <body>{children}</body>
    </html>
  );
}`}</code></pre>
          <p className="mt-3 text-slate-700">
            For multi-language sites using a <code>[locale]</code> segment, pass locale
            through:
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-xs leading-snug text-slate-100"><code>{`// app/[locale]/layout.tsx
export default async function LocaleLayout({ children, params }) {
  const { locale } = await params;
  return <html lang={locale}>...</html>;
}`}</code></pre>
        </section>

        <section id="images" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">
            The Image component — alt text and decorative images
          </h2>
          <p className="mt-3 text-slate-700">
            <code>next/image</code> requires an <code>alt</code> prop — but TypeScript
            won&apos;t stop you from passing an empty string or a filename.
            <strong> Empty <code>alt=&quot;&quot;</code> is correct</strong> for
            decorative images that carry no information. <strong>Never</strong> put the
            filename or &quot;image&quot;.
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-xs leading-snug text-slate-100"><code>{`// ✅ Informative image — describe what it shows
<Image src={hero} alt="Accessibility report showing 3 critical violations" />

// ✅ Decorative image — empty alt tells screen readers to skip
<Image src={splash} alt="" />

// ❌ Never this — screen readers read it literally
<Image src={logo} alt="logo.png" />
<Image src={ad} alt="image" />`}</code></pre>
          <p className="mt-3 text-slate-700">
            Logos are tricky: <code>alt=&quot;axle&quot;</code> is fine if the brand name
            is itself information. If the logo sits next to a text heading that already
            says &quot;axle&quot;, use <code>alt=&quot;&quot;</code> to avoid repetition for
            screen-reader users.
          </p>
        </section>

        <section id="links" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">Link vs anchor vs button</h2>
          <p className="mt-3 text-slate-700">
            <code>next/link</code> renders an anchor. Use it for navigation. Use a{" "}
            <code>&lt;button&gt;</code> for actions that don&apos;t change URL (toggle a
            menu, open a modal, submit a form). This is WCAG 4.1.2 compliance — screen
            readers announce &quot;link&quot; vs &quot;button&quot; differently.
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-xs leading-snug text-slate-100"><code>{`// ✅ Navigates to a route
<Link href="/pricing">See pricing</Link>

// ✅ Action, no URL change
<button onClick={() => setMenuOpen(true)}>Open menu</button>

// ❌ Confusing for assistive tech
<Link href="#" onClick={() => doSomething()}>Open menu</Link>

// ❌ Worse — div doesn't get keyboard focus at all
<div onClick={() => navigate()} role="link">Go</div>`}</code></pre>
          <p className="mt-3 text-slate-700">
            Opening a link in a new tab? Include visually-hidden text or an explicit
            indicator — users on screen readers can&apos;t see the <code>target=&quot;_blank&quot;</code>{" "}
            behaviour.
          </p>
        </section>

        <section id="forms" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">
            Form labels and error messaging
          </h2>
          <p className="mt-3 text-slate-700">
            Placeholder text is not a label. When the user starts typing, it disappears —
            and screen readers often don&apos;t announce placeholders at all. WCAG 3.3.2
            requires every input have a programmatically associated label.
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-xs leading-snug text-slate-100"><code>{`// ✅ Explicit label
<label htmlFor="email">Email address</label>
<input id="email" type="email" placeholder="you@example.com" required />

// ✅ Visually hidden label (when design requires no visible label)
<label htmlFor="search" className="sr-only">Search</label>
<input id="search" type="search" placeholder="Search…" />

// ❌ Placeholder-as-label
<input type="email" placeholder="Email address" />`}</code></pre>
          <p className="mt-3 text-slate-700">
            Error messages must be announced, not just coloured red. Associate them via{" "}
            <code>aria-describedby</code> so screen readers read them when the user focuses
            the field:
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-xs leading-snug text-slate-100"><code>{`<label htmlFor="email">Email</label>
<input
  id="email"
  aria-invalid={!!error}
  aria-describedby={error ? "email-error" : undefined}
/>
{error && (
  <p id="email-error" role="alert" className="text-red-600">
    {error}
  </p>
)}`}</code></pre>
        </section>

        <section id="focus" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">
            Focus management on client-side navigation
          </h2>
          <p className="mt-3 text-slate-700">
            When a user clicks <code>next/link</code> in the App Router, focus stays where
            it was. On a real document navigation, focus would have moved to the start of
            the page. For screen-reader users this is a disorientation.
          </p>
          <p className="mt-3 text-slate-700">
            Next.js 14+ partially handles this via the <code>focus-visible</code> hints on
            route changes, but for visually-hidden skip links and heading-focus patterns
            you still need manual focus management. A common pattern:
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-xs leading-snug text-slate-100"><code>{`// app/layout.tsx — skip link that jumps to main content
<body>
  <a href="#main-content" className="sr-only focus:not-sr-only ...">
    Skip to main content
  </a>
  <main id="main-content" tabIndex={-1}>
    {children}
  </main>
</body>

// Page-level components: focus the h1 on mount for SPA navigation
useEffect(() => {
  document.getElementById("page-title")?.focus();
}, [pathname]);`}</code></pre>
        </section>

        <section id="headings" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">
            Heading hierarchy across the App Router tree
          </h2>
          <p className="mt-3 text-slate-700">
            WCAG 2.4.6 requires headings reflect the information hierarchy. A page must
            have exactly one <code>h1</code> and heading levels must not skip (no{" "}
            <code>h1</code> → <code>h3</code>).
          </p>
          <p className="mt-3 text-slate-700">
            The App Router nested layout model makes this tricky. If your root{" "}
            <code>layout.tsx</code> renders a header with an <code>h1</code> (e.g., your
            product name), then your page components should start at <code>h2</code>.
            Worse, nested route segments can accidentally introduce <code>h1</code>s that
            collide with the layout&apos;s.
          </p>
          <p className="mt-3 text-slate-700">
            Rule of thumb: <strong>only the leaf page renders the <code>h1</code></strong>.
            Layouts render <code>h2</code> and below for any visible headings.
          </p>
        </section>

        <section id="dialog" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">
            Dialogs and overlays — the 5 requirements
          </h2>
          <p className="mt-3 text-slate-700">
            Modal dialogs are where most WCAG violations cluster. If you ship a modal, it
            must:
          </p>
          <ol className="mt-3 list-decimal space-y-2 ps-6 text-slate-700">
            <li>Move keyboard focus <em>into</em> the dialog on open, and back to the trigger on close.</li>
            <li>Trap Tab inside the dialog while it&apos;s open (so users can&apos;t tab out).</li>
            <li>Dismiss on <kbd>Escape</kbd> key.</li>
            <li>Have <code>role=&quot;dialog&quot;</code> and <code>aria-modal=&quot;true&quot;</code> (or use the native <code>&lt;dialog&gt;</code> element).</li>
            <li>Have a visible accessible name (<code>aria-labelledby</code> pointing to a heading inside the dialog).</li>
          </ol>
          <p className="mt-3 text-slate-700">
            The native <code>&lt;dialog&gt;</code> element handles focus trap and Escape
            automatically. Use it unless you have a reason not to — most component libraries
            still hand-roll this and get it wrong.
          </p>
        </section>

        <section id="ci" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">
            CI setup — block regressions in every PR
          </h2>
          <p className="mt-3 text-slate-700">
            The manual checks above are a one-time cleanup. To keep them clean, put
            axe-core in CI. Drop this into <code>.github/workflows/accessibility.yml</code>:
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-xs leading-snug text-slate-100"><code>{`name: Accessibility
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  axle:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: asafamos/axle-action@v1
        with:
          install-command: npm ci
          build-command: npm run build
          start-command: npm start
          wait-on-port: "3000"
          fail-on: serious
          with-ai-fixes: "true"
          anthropic-api-key: \${{ secrets.ANTHROPIC_API_KEY }}`}</code></pre>
          <p className="mt-3 text-slate-700">
            What you get: a sticky PR comment with every violation grouped by severity, a
            downloadable JSON + Markdown report, and a non-zero exit code when violations
            cross the <code>fail-on</code> threshold — which blocks merge if you require
            the check.
          </p>
          <p className="mt-3 text-slate-700">
            This is the same pipeline we use on axle&apos;s own Next.js marketing site.
            If our own PR regresses accessibility, our own build fails first.
          </p>

          <div className="mt-6 flex flex-wrap gap-3">
            <a
              href="https://github.com/marketplace/actions/axle-accessibility-compliance-ci"
              target="_blank"
              rel="noopener"
              className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-700"
            >
              Install the GitHub Action →
            </a>
            <a
              href="https://www.npmjs.com/package/axle-vercel-plugin"
              target="_blank"
              rel="noopener"
              className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-800 hover:bg-slate-100"
            >
              Vercel plugin →
            </a>
            <Link
              href="/"
              className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-800 hover:bg-slate-100"
            >
              ← Back to axle
            </Link>
          </div>
        </section>

        <footer className="mt-12 border-t border-slate-200 pt-6 text-sm text-slate-500">
          <p>
            Updated: 21 April 2026. Covers Next.js 14–16. App Router patterns shown; Pages
            Router is broadly similar but focus-management timing differs. Feedback
            welcome:{" "}
            <a className="underline" href="mailto:asaf@amoss.co.il">
              asaf@amoss.co.il
            </a>
            .
          </p>
        </footer>
      </article>
    </main>
  );
}

// app/guides/vue-accessibility/page.tsx
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Vue accessibility — WCAG 2.1 AA for Vue 3, Nuxt, Pinia (2026)",
  description:
    "Practical accessibility for Vue 3 and Nuxt: single-file-component patterns, template directives, useId, router focus management, vitest-axe + Playwright, and CI. Written for developers targeting EAA 2025 / ADA / תקנה 35.",
  keywords: [
    "Vue accessibility",
    "Vue 3 a11y",
    "Nuxt accessibility",
    "vitest-axe",
    "Vue WCAG",
    "Vue EAA compliance",
    "axle",
  ],
  openGraph: {
    title: "Vue accessibility — a practical WCAG 2.1 AA guide",
    description:
      "How to build accessible Vue 3 + Nuxt applications: semantics, useId, focus management, testing, CI.",
    type: "article",
    locale: "en_US",
  },
  alternates: { canonical: "/guides/vue-accessibility" },
};

export default function VueAccessibilityPage() {
  return (
    <main className="min-h-screen bg-slate-50">
      <article className="mx-auto max-w-3xl px-6 py-12">
        <p className="text-xs font-semibold uppercase tracking-wider text-slate-500">
          Stack · Vue / Nuxt · accessibility engineering
        </p>
        <h1 className="mt-2 text-4xl font-bold tracking-tight text-slate-900">
          Vue accessibility — the practical guide
        </h1>
        <p className="mt-4 text-lg text-slate-700">
          Vue 3 gives you the primitives for accessible components — scoped slots,
          composables, and the <code>useId</code> composable in 3.5+. Nuxt adds
          file-based routing, which is where most Vue accessibility bugs come from:
          focus doesn&apos;t move, page titles don&apos;t update, and the assistive-tech
          story breaks at route transitions. This guide covers the Vue-specific
          patterns that matter for WCAG 2.1 AA — written for teams shipping to
          markets under EAA 2025, ADA, and <Link href="/he/takana-35" className="underline">Israeli תקנה 35</Link>.
        </p>

        <nav className="mt-8 rounded-lg border border-slate-200 bg-white p-4 text-sm">
          <div className="text-xs font-semibold uppercase tracking-wider text-slate-500">
            Contents
          </div>
          <ol className="mt-2 list-decimal space-y-1 ps-6 text-slate-700">
            <li><a className="hover:underline" href="#semantics">Component semantics</a></li>
            <li><a className="hover:underline" href="#forms">Forms with useId</a></li>
            <li><a className="hover:underline" href="#focus">Focus management across routes</a></li>
            <li><a className="hover:underline" href="#dialogs">Dialogs and the &lt;dialog&gt; element</a></li>
            <li><a className="hover:underline" href="#live">Live regions for async state</a></li>
            <li><a className="hover:underline" href="#testing">Testing with vitest-axe + Playwright</a></li>
            <li><a className="hover:underline" href="#nuxt">Nuxt specifics</a></li>
            <li><a className="hover:underline" href="#ci">CI pipeline</a></li>
          </ol>
        </nav>

        <section id="semantics" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">Component semantics</h2>
          <p className="mt-3 text-slate-700">
            The cardinal Vue sin: <code>&lt;div @click=&quot;...&quot;&gt;</code> for
            things that should be <code>&lt;button&gt;</code>. Screen readers
            don&apos;t announce <code>div</code>s as interactive, and they aren&apos;t
            keyboard-focusable by default. The fix is almost always the native
            element:
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-sm text-slate-100">
{`<!-- Wrong -->
<div class="btn" @click="handle">Submit</div>

<!-- Right -->
<button type="button" class="btn" @click="handle">
  Submit
</button>`}
          </pre>
          <p className="mt-3 text-slate-700">
            When you genuinely need a custom interactive pattern (tab list, combobox,
            disclosure), follow the{" "}
            <a className="underline" href="https://www.w3.org/WAI/ARIA/apg/" target="_blank" rel="noopener">
              ARIA Authoring Practices Guide
            </a>{" "}
            and expose the right roles and state. The <code>headlessui/vue</code>{" "}
            library implements most common patterns correctly; use it rather than
            hand-rolling.
          </p>
        </section>

        <section id="forms" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">Forms with useId</h2>
          <p className="mt-3 text-slate-700">
            Vue 3.5 added <code>useId()</code> — use it. Before 3.5 (and in
            component libraries that still target 3.4), a ref-counter composable is
            acceptable but prefer upgrading.
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-sm text-slate-100">
{`<script setup lang="ts">
import { useId } from 'vue'

const props = defineProps<{
  label: string
  error?: string
}>()
const id = useId()
const errorId = useId()
</script>

<template>
  <div>
    <label :for="id">{{ label }}</label>
    <input
      :id="id"
      :aria-invalid="!!error"
      :aria-describedby="error ? errorId : undefined"
    />
    <p v-if="error" :id="errorId" role="alert">{{ error }}</p>
  </div>
</template>`}
          </pre>
          <p className="mt-3 text-slate-700">
            Key points: the <code>&lt;label for&gt;</code> wiring is what lets screen
            readers announce the field name on focus. The{" "}
            <code>aria-describedby</code> wiring is what couples the error message to
            the input. <code>role=&quot;alert&quot;</code> makes the error itself
            announce the moment it renders.
          </p>
        </section>

        <section id="focus" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">
            Focus management across routes
          </h2>
          <p className="mt-3 text-slate-700">
            Vue Router (and Nuxt&apos;s router) does not move focus on navigation.
            Keyboard and screen-reader users are left focused on the previous page&apos;s
            activation point — a WCAG 2.4.3 failure. Fix it globally:
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-sm text-slate-100">
{`// router/index.ts
import { createRouter, createWebHistory } from 'vue-router'

const router = createRouter({
  history: createWebHistory(),
  routes: [/* ... */],
})

router.afterEach(() => {
  // Defer to next tick so the new page has mounted
  requestAnimationFrame(() => {
    const target = document.querySelector<HTMLElement>('h1, [role="main"]')
    if (target) {
      target.setAttribute('tabindex', '-1')
      target.focus({ preventScroll: false })
    }
  })
})

export default router`}
          </pre>
          <p className="mt-3 text-slate-700">
            Combine with updating <code>document.title</code> in the route meta or
            via <code>useHead</code> (Nuxt) / <code>@vueuse/head</code>. Screen readers
            read the title on navigation in many combinations.
          </p>
        </section>

        <section id="dialogs" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">
            Dialogs and the &lt;dialog&gt; element
          </h2>
          <p className="mt-3 text-slate-700">
            The native <code>&lt;dialog&gt;</code> element handles focus trap,
            backdrop, and Escape-to-close for you. Prefer it to a custom <code>role=&quot;dialog&quot;</code>{" "}
            <code>div</code>:
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-sm text-slate-100">
{`<script setup lang="ts">
import { ref, watch } from 'vue'

const props = defineProps<{ open: boolean; label: string }>()
const emit = defineEmits<{ close: [] }>()
const dialogRef = ref<HTMLDialogElement | null>(null)

watch(
  () => props.open,
  (open) => {
    if (!dialogRef.value) return
    if (open) dialogRef.value.showModal()
    else dialogRef.value.close()
  },
)
</script>

<template>
  <dialog
    ref="dialogRef"
    :aria-label="label"
    @close="emit('close')"
    class="rounded-lg p-6"
  >
    <slot />
  </dialog>
</template>`}
          </pre>
          <p className="mt-3 text-slate-700">
            If you need headless behaviour (custom animation, portal, nested
            dialogs), <code>@headlessui/vue</code>&apos;s <code>Dialog</code> is the
            path of least breakage. Do not hand-roll focus trap — the known-bad
            patterns always bite.
          </p>
        </section>

        <section id="live" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">
            Live regions for async state
          </h2>
          <p className="mt-3 text-slate-700">
            Async operations that complete visibly — &ldquo;Added to cart&rdquo;
            toasts, search-result counts, form-submit success — need to announce to
            screen readers via an ARIA live region.
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-sm text-slate-100">
{`<template>
  <div
    role="status"
    aria-live="polite"
    aria-atomic="true"
    class="sr-only"
  >
    {{ message }}
  </div>
</template>

<script setup lang="ts">
defineProps<{ message: string }>()
</script>`}
          </pre>
          <p className="mt-3 text-slate-700">
            For urgent updates (errors, time-sensitive warnings) use{" "}
            <code>aria-live=&quot;assertive&quot;</code>. Use it sparingly — assertive
            interrupts whatever the user was listening to.
          </p>
        </section>

        <section id="testing" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">
            Testing with vitest-axe + Playwright
          </h2>
          <p className="mt-3 text-slate-700">
            Component-level with vitest and <code>@vitest-axe/vitest-axe</code>:
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-sm text-slate-100">
{`// ProductCard.test.ts
import { describe, it, expect } from 'vitest'
import { render } from '@testing-library/vue'
import { axe, toHaveNoViolations } from 'vitest-axe'
import ProductCard from './ProductCard.vue'

expect.extend({ toHaveNoViolations })

describe('ProductCard', () => {
  it('has no accessibility violations', async () => {
    const { container } = render(ProductCard, {
      props: { name: 'T-shirt', price: 19.99 },
    })
    const results = await axe(container)
    expect(results).toHaveNoViolations()
  })
})`}
          </pre>
          <p className="mt-3 text-slate-700">
            Page-level with Playwright and <code>@axe-core/playwright</code>:
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-sm text-slate-100">
{`// e2e/home.spec.ts
import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test('homepage is accessible', async ({ page }) => {
  await page.goto('/')
  const { violations } = await new AxeBuilder({ page }).analyze()
  expect(violations).toEqual([])
})`}
          </pre>
        </section>

        <section id="nuxt" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">Nuxt specifics</h2>
          <ul className="mt-3 list-disc space-y-2 ps-6 text-slate-700">
            <li>
              <strong>Page title per route</strong> — use <code>useHead({'{'} title: &apos;...&apos; {'}'})</code>{" "}
              in every page component. Nuxt&apos;s default is the app name only, which
              fails WCAG 2.4.2.
            </li>
            <li>
              <strong>lang on html</strong> — set via <code>useHead({'{'} htmlAttrs: {'{'} lang: &apos;en&apos; {'}'} {'}'})</code> or through the app config in{" "}
              <code>nuxt.config.ts</code>.
            </li>
            <li>
              <strong>Image component</strong> — <code>&lt;NuxtImg&gt;</code> requires{" "}
              <code>alt</code> explicitly. Decorative images: <code>alt=&quot;&quot;</code>. Never omit.
            </li>
            <li>
              <strong>Nuxt Content</strong> — if you render markdown via{" "}
              <code>&lt;ContentDoc&gt;</code>, audit the generated output; heading
              hierarchy from author content often skips levels.
            </li>
            <li>
              <strong>Nuxt UI / Nuxt UI Pro</strong> — the default components are
              broadly accessible; verify before shipping overrides.
            </li>
          </ul>
        </section>

        <section id="ci" className="mt-10">
          <h2 className="text-2xl font-bold text-slate-900">CI pipeline</h2>
          <p className="mt-3 text-slate-700">
            Drop this in{" "}
            <code>.github/workflows/accessibility.yml</code> to fail PRs on new
            WCAG violations:
          </p>
          <pre tabIndex={0} className="mt-3 overflow-x-auto rounded-md bg-slate-900 p-4 text-sm text-slate-100">
{`name: Accessibility
on: [pull_request]
jobs:
  a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asafamos/axle-action@v1
        with:
          url: \${{ secrets.PREVIEW_URL }}
          fail-on: serious`}
          </pre>
          <p className="mt-3 text-slate-700">
            For a Vercel / Netlify preview flow, install the{" "}
            <code>axle-vercel-plugin</code> or <code>axle-netlify-plugin</code>{" "}
            directly so scans run inside the build.
          </p>

          <div className="mt-6 flex flex-wrap gap-3">
            <a
              href="https://github.com/marketplace/actions/axle-accessibility-compliance-ci"
              target="_blank"
              rel="noopener"
              className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-700"
            >
              Install the GitHub Action →
            </a>
            <Link
              href="/statement"
              className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-800 hover:bg-slate-100"
            >
              Statement generator
            </Link>
            <Link
              href="/guides"
              className="rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-800 hover:bg-slate-100"
            >
              ← All guides
            </Link>
          </div>
        </section>

        <footer className="mt-12 border-t border-slate-200 pt-6 text-sm text-slate-500">
          Updated: 22 April 2026. Covers Vue 3.5+ and Nuxt 3.14+. Not legal advice.{" "}
          <a className="underline" href="mailto:asaf@amoss.co.il">
            asaf@amoss.co.il
          </a>
          .
        </footer>
      </article>
    </main>
  );
}
